version: "3.8"

services:

  config-server:
    build:
      context: ./config-server
    container_name: config-server-service
    ports:
      - 8888:8888
    depends_on:
      - rabbitmq
      - maildev
      - redis
      - zipkin

  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureka-service
    ports:
      - 8761:8761

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway-service
    ports:
      - 8861:8861
    depends_on:
      - eureka-server
      - config-server

  customer-service:
    build:
      context: ./customer-service
    container_name: customer-service
    ports:
      - 8082:8082
    depends_on:
      - eureka-server
      - config-server

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    ports:
      - 8083:8083
    depends_on:
      - eureka-server
      - config-server

  order-service:
    build:
      context: ./order-service
    container_name: order-service
    ports:
      - 8081:8081
    depends_on:
      - customer-service
      - product-service
      - eureka-server
      - config-server

  mail-service:
    build:
      context: ./mail-service
    container_name: mail-service
    ports:
      - 8084:8084
    depends_on:
      - rabbitmq
      - config-server

  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - "1080:1080"  # Web arayüzü için
      - "1025:1025"  # SMTP sunucusu için
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"       # uygulamaların baglandigi port
      - "15672:15672"     # Web arayüzü (RabbitMQ UI)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"


volumes:
  rabbitmq_data:
  redis-data: